=== HimanshuGarg47/XML-PHP/2ndLabphp/external.xsd
<?xml version="1.0" encoding="UTF-8"?>
<ms:schema xmlns:ms="http://www.w3.org/2001/XMLSchema">
<ms:element name= "movies">
    <ms:complexType>
        <ms:sequence>
            <ms:element name="movie" maxOccurs="unbounded">
                <ms:complexType>
                    <ms:sequence>
                        <ms:element name="title" type="ms:string"/>
                        <ms:element name="year" type="ms:integer"/>
                        <ms:element name="genre" type="ms:string"/>

                    </ms:sequence>
                </ms:complexType>
            </ms:element>
        </ms:sequence>
    </ms:complexType>
</ms:element>
</ms:schema>

=== HimanshuGarg47/XML-PHP/2ndLabphp/3bpractical.xml
<?xml version="1.0" encoding="UTF-8"?>

<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="external.xsd">

<movie>
    <title> Mr. India </title>
    <year> 2003 </year>
    <genre> Comedy</genre>  

</movie>

<movie>
    <title> Krish</title>
    <year> 2008</year>
    <genre> Romantic </genre>

</movie>
</movies>
